### ISSUE TITLE
[ERROR] Crashing after selecting a team.

### ISSUE THREAD

**Issue by SmokeyMcGames** [ssypchenko/cs2-gungame#2]
Server crashes when joining and selecting a side. CSSharp log shows InvocationException.

![Untitled-1](https://github.com/ssypchenko/cs2-gungame/assets/63999573/0a47c68b-2dfb-4979-b2ec-06cd474590a2)

Here's the CSSharp log as well

[log-all20231229.txt](https://github.com/ssypchenko/cs2-gungame/files/13797209/log-all20231229.txt)

Running the server with the plugin removed from the CSSharp plugins folder has the server running without issue.

**Comment by ssypchenko** [comment]
As with the another issue posted, I think that the reason for the issue somehow connected with the Server.MaxPlayers variable on your server. Could you please confirm the maximum number of players on your server just in case?

**Comment by ssypchenko** [comment]
And do you have Windows or linux server?

**Comment by SmokeyMcGames** [comment]
This is a windows server and I've been setting max players to 20 in the start command line batch. There seems to not be any change when changing the amount of players when it comes to the crashing. Also just want to add that I used your recommendation for +game_type 0 +game_mode 0 in the command batch as well when starting the server.

**Comment by LawrenceWeng** [comment]
Thanks for putting this mod together, but I also have this same issue. I set the server to limit lower (such as 32, but have tried as low as 2), but this does not seem to fix the problem.

I am also on Windows and am running your version from today (v1.03)

Thanks again, looking forward to playing this with friends!

**Comment by ssypchenko** [comment]
> Thanks for putting this mod together, but I also have this same issue. I set the server to limit lower (such as 32, but have tried as low as 2), but this does not seem to fix the problem. `.\cs2 -dedicated +game_type 0 +game_mode 0 +map de_dust2 -maxplayers 2`
> 
> I am also on Windows and am running your version from today (v1.03)
> 
> Thanks again, looking forward to playing this with friends!

Error related to the player quantity is another issue:
https://github.com/ssypchenko/cs2-gungame/issues/1

This issue is with the problem that the plugin can't remove weapons from players on Windows at the moment when the player joins a team. :(

**Comment by ssypchenko** [comment]
I raised an issue on CSS Git Hub about it.

**Comment by garik-76** [comment]
День добрый!
Как понять что плагин gg2 загружен? После входа на сервер перед тем как он выдаст ошибку начинается отчет времени разогревочного раунда. Время для разогрева сервер берет из конфигурации gamemode_casual а не из gungame.json.
Сервер Windows.
![meta](https://github.com/ssypchenko/cs2-gungame/assets/156197673/7670945b-3f27-4ae1-b0bf-2267dd429de6)
![load gg](https://github.com/ssypchenko/cs2-gungame/assets/156197673/3010c5a1-75ca-434a-8e42-5893b6024906)
![gg_version](https://github.com/ssypchenko/cs2-gungame/assets/156197673/f2335456-b410-4aaf-b449-2cafa43b9405)

**Comment by ssypchenko** [comment]
> День добрый! Как понять что плагин gg2 загружен? 

Would you please ask for support in Discord here:
https://discord.com/channels/1160907911501991946/1189008468439474226

**Comment by garik-76** [comment]
> css_plugins list
Команда работает

**Comment by ssypchenko** [comment]
> > css_plugins list
> Команда работает
Супер. Я удалю твои посты отсюда, т.к. они не по теме топика. Переходи для поддержки в Дискорд, пожалуйста. Ссылка выше. 
Once again, support is in Discord

**Comment by LawrenceWeng** [comment]
Looks like there is a workaround at least. :) Thanks so much @ssypchenko for all your work on this! Looking forward to playing with my friends!

> I have also faced this issue on my local Windows server, here's what I've been using in the meantime
> 
> ```cs
> // TODO: once this stops crashing on windows use it there too
> if (Environment.OSVersion.Platform == PlatformID.Unix)
> {
>     player.RemoveWeapons();
> }
> else
> {
>     if (player.PlayerPawn.Value == null || player.PlayerPawn.Value.WeaponServices == null)
>     {
>         return;
>     }
>         
>     foreach (var weapon in player.PlayerPawn.Value.WeaponServices.MyWeapons)
>     {
>         if (weapon is not { IsValid: true, Value.IsValid: true })
>         {
>             continue;
>         }
>         
>         player.PlayerPawn.Value.RemovePlayerItem(weapon.Value);
>         weapon.Value.Remove();
>     }
> }
> ```

**Comment by LawrenceWeng** [comment]
I made a fork and tried to fix it myself. https://github.com/LawrenceWeng/cs2-gungame

The error is gone, but now it just exits without any error messages. I am too new at this to know how to debug any further.
![image](https://github.com/ssypchenko/cs2-gungame/assets/5121389/43ea74cc-d9d3-493e-9fc7-909452f09c3d)

**Comment by ssypchenko** [comment]
> I made a fork and tried to fix it myself. https://github.com/LawrenceWeng/cs2-gungame
> 

This is a good idea about the workaround. Unfortunately, I'm quite busy testing and fixing some small errors so I did not have time to implement your suggestion. I installed the Windows server for tests and I will try to test the workaround. But please understand me, my main server is on linux and I focused to have the working plugin without daily issues on my server. 
ANyway, I'll check and keep you posted.

**Comment by ssypchenko** [comment]
With CSS v153 the issue is fixed.
