### ISSUE TITLE
Disable custom audio/lower volume

### ISSUE THREAD

**Issue by Haelnorr** [ssypchenko/cs2-gungame#6]
The audio files that play (configured in gungame.json) are extremely loud, and I cannot work out how to lower their volume or disable them entirely.

**Comment by ssypchenko** [comment]
It is impossible to manage the volume right now :( 
You have these options:
- Sound Control: Players can now toggle plugin sounds on/off using the !music command. Preferences are saved in the database. (I'm not 100% sure that it works correctly in the release v1.0.3. I try to fix and improve it in the next release)
- delete sounds from the configuration at all
- use these "individual" settings (it is manually on client):
Temporarily solution for sound volume:
bind O “incrementvar snd_toolvolume 0 1 0.2” 
This command will assign to the letter O the ability to change the volume of sounds in steps of 0.2 from 0 to 1. As soon as the volume becomes 1, with the next press it will become equal to 0, and then again cyclically.
This way you can choose a comfortable volume for the plug-in sounds. And this does not apply to other standard sounds of shooting, footsteps, etc.

**Comment by pnallinger** [comment]
thank you! can you tell me why? is this sound command not implemented on cs2? with sounds it is unplayable imo or i am missing a setting. i will delete all sounds for now

**Comment by ssypchenko** [comment]
Emit Sound with volume control as it was in SourceMode has not been developed in CounterStrikeSharp yet. 
!music command turns off and back on extra sounds now.
