### ISSUE TITLE
1.0.4 Server Crash

### ISSUE THREAD

**Issue by Crooonch** [ssypchenko/cs2-gungame#7]
Updated to version 1.0.4 and haven't been able to get it to work. Everything worked perfect in the last update, this one the game loads up but doesn't seem to load the warmup nades and crashes while using any commands such as !rank. This is on a dedicated linux server. Any help you can provide would be great :)

**Comment by ssypchenko** [comment]
Uploaded a new version 1.0.5. I uploaded it to my server and played with it. It works fine. Please try it. If there are still problems, could you please try it from scratch - delete all your settings and database, load a new version and try again.

**Comment by Crooonch** [comment]
Ok I tried that and it server entirely before the game loads. It looks like I'm seeing this in the log:

[GunGame_Stats] ******* StatsManager: Failed to load database configuration from
[INFO] (plugin:CS2_GunGame) [GunGame_Stats] ******* StatsManager: Failed to load database configuration from
[GunGame_Online - FATAL] InitializeDatabaseConnection: Database connection error: Object reference not set to an instance of an object., working without online reports

I never had a database setup for 1.0.3, how do I link the database? 

Thank you for the help :)

**Comment by Crooonch** [comment]
Update: I figured out the database connection but the gungame plugin doesn't load the weapons anymore. I'll roll back to 1.0.3 for now

**Comment by ssypchenko** [comment]
> Update: I figured out the database connection but the gungame plugin doesn't load the weapons anymore. I'll roll back to 1.0.3 for now

I'm pretty sure that version 1.0.5 works correctly. I would advise you to delete plugin folder, cfg/gungame folder, these two files
csgo/cfg/gungame-db.json
csgo/cfg/gungame-db.sqlite

Then turn off the server, copy plugin folder and cfg/gungame folder and try again.

**Comment by Crooonch** [comment]
Thank you for the responses. It looks like it was a server issue. Fresh install of everything and it all works.

Also thanks for the great plugin! Love it!
