### ISSUE TITLE
[BUG] Server crash when player wins with knife

### ISSUE THREAD

**Issue by kus** [ssypchenko/cs2-gungame#9]
Since the latest CS2 update, now when a player wins (by knifing) it crashes.

```
Metamod:Source: 2.0.0-1282
CounterStrikeSharp: 163
GunGame: 1.0.7
```

Log:
```
Feb  9 09:15:58 cs2-server: Gh0stye killed Kus with glock
Feb  9 09:16:08 cs2-server: Kus killed Gh0stye with knife_karambit
Feb  9 09:16:08 cs2-server: 09:16:08 [INFO] (plugin:CS2_GunGame) Winner Kus
Feb  9 09:16:08 cs2-server: 09:16:08 [INFO] (plugin:CS2_GunGame) Kus won, wins was 0
Feb  9 09:16:09 cs2-server: [GunGame_Stats] Saved player wins for Kus - 1
Feb  9 09:16:09 cs2-server: Call EndMultiplayerGame in 5 seconds
Feb  9 09:16:09 cs2-server kernel: [  717.955421] show_signal_msg: 33 callbacks suppressed
Feb  9 09:16:09 cs2-server kernel: [  717.955424] cs2[1875]: segfault at 10 ip 00007fd99a4a88e1 sp 00007fff18160e40 error 4 in libserver.so[7fd99a04b000+47d000]
Feb  9 09:16:09 cs2-server kernel: [  717.955435] Code: 41 54 49 89 d4 48 89 f2 53 4c 89 c3 48 83 ec 18 48 8d 05 92 f1 6c 00 48 8b 30 e8 0a 7e 01 00 48 8b 45 c0 48 8d 75 c8 45 89 f1 <49> 8b 7f 10 49 89 d8 4c 89 e9 4c 89 e2 48 89 45 c8 e8 19 c1 ff ff
```

**Comment by ssypchenko** [comment]
@kus we should wait for the latest update of CounterStrikeSharp or you can update your gamedata yourself from here
https://pastebin.com/MEsUt0mu

This specific part is responsible for this crash: 
`"LegacyGameEventListener": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\x15\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xD2\\x74\\x2A\\x85\\xC9\\x74",
      "linux": "\\x48\\x8B\\x05\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xC0\\x74\\x2A\\x83\\xFF\\x3F\\x76\\x2A\\x31\\xC0"
    }
  },`

But some other parts are important too.

**Comment by kus** [comment]
> @kus we should wait for the latest update of CounterStrikeSharp or you can update your gamedata yourself from here https://pastebin.com/MEsUt0mu
> 
> This specific part is responsible for this crash: `"LegacyGameEventListener": { "signatures": { "library": "server", "windows": "\\x48\\x8B\\x15\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xD2\\x74\\x2A\\x85\\xC9\\x74", "linux": "\\x48\\x8B\\x05\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xC0\\x74\\x2A\\x83\\xFF\\x3F\\x76\\x2A\\x31\\xC0" } },`
> 
> But some other parts are important too.

@ssypchenko thanks, confirming that has fixed it.
